# .github/workflows/ui-tests-ci.yml

name: auto_BDD UI report

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-and-deploy-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run UI Tests with Pytest
        run: pytest --alluredir=./allure-results

      # 新增步骤
      - name: Get historical report data for trendline
        # 从 gh-pages 分支（上次部署报告的地方）拉取历史数据
        run: |
          mkdir -p allure-history
          git clone --branch gh-pages --single-branch https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git allure-history
          # 将历史数据拷贝到本次测试结果中
          cp -r allure-history/history allure-results/history || true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Manually Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip
          unzip allure-2.29.0.zip
          echo "$(pwd)/allure-2.29.0/bin" >> $GITHUB_PATH

      - name: Generate Allure Report
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          # 保持历史记录，不清空 gh-pages 分支的 git 历史
          keep_files: true
