# .github/workflows/ui-tests-ci.yml

name: auto_BDD UI report

on:
  push:
    branches: [ main, develop ]
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  build-test-and-deploy-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run UI Tests with Pytest
        run: pytest --alluredir=./allure-results

      # update
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1
        with:
          # 修正: 'results_path' 应为 'allure_results'
          allure_results: allure-results
          # 默认生成的报告文件夹就是 allure-report

      # update
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 部署由上一步默认生成的 'allure-report' 文件夹
          publish_dir: ./allure-report
