# .github/workflows/ui-tests-ci.yml

name: auto_BDD UI report

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-and-deploy-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run UI Tests with Pytest
        run: pytest --alluredir=./allure-results

      - name: Get historical report data for trendline
        run: |
          mkdir -p allure-history
          git clone --branch gh-pages --single-branch https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git allure-history
          cp -r allure-history/history allure-results/history || true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Manually Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip
          unzip allure-2.29.0.zip
          echo "$(pwd)/allure-2.29.0/bin" >> $GITHUB_PATH

      - name: Generate Allure Report
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          keep_files: true

      # 邮件通知
      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.126.com
          server_port: 465
          
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          
          subject: "GHA build - ${{ github.repository }} (Build ${{ job.status == 'success' && 'success' || 'fail' }})"
          
          # 邮件正文
          html_body: |
            <h3>自动化测试构建已完成！</h3>
            <p><b>构建状态: ${{ job.status == 'success' && '✅ success' || '❌ fail' }}</b></p>
            <p>仓库: ${{ github.repository }}</p>
            <p>触发事件: ${{ github.event_name }}</p>
            <hr>
            <p>
            ${{ job.status == 'success' && '最新的 Allure 测试报告已生成，请点击以下链接查看：<br><a href="https://lanyangyg.github.io/auto_BDD/">https://lanyangyg.github.io/auto_BDD/</a>' || '构建失败，请点击以下链接查看详细日志：<br><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">点击这里查看构建日志</a>' }}
            </p>
            <br><br>
            <p><i>此邮件由 GitHub Actions 自动发送。</i></p>

          to: fnnnfnnfn@126.com
          from: GitHub Actions CI
